### 1. Imports

In [1]:
# Import the pandas library - conventionally imported as "pd"
import pandas as pd

### 2. Load Data

[Kaggle](https://www.kaggle.com/) is an amazing platform for data-science created by Google.

On Kaggle there are hundreds of available datasets. For these tutorials I'll be using [The Ames Housing](https://www.kaggle.com/c/house-prices-advanced-regression-techniques/data) dataset which can be downloaded from [Kaggle](https://www.kaggle.com/) after creating an account.

This dataset was compiled by Dean De Cock for use in data science education. It's an incredible alternative for data scientists looking for a modernized and expanded version of the often cited Boston Housing dataset. 

* We use the dataframe constructor to read data from .csv files.

* We drop the Id index column, because Pandas autogenerates an integer-index, and we don't need this twice.

* The `df.head()` function prints the first five lines of any dataframe and Jupyter renders in nicely in html.

In [2]:
df = pd.read_csv('data/train.csv')

df = df.drop(columns='Id')

df.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

### 3. Examine Data

When you download a data-package from Kaggle there are usually four files:

* _data_description.txt_
* _sample_submission.csv_ 
* _test.csv_
* _train.csv_

Some of these files have Kaggle specific uses, here we'll only use _train.csv_ and _data_description.txt_ files.

_train.csv_ contains the bulk of the data, while _data_description.txt_ contains descriptions of each feature/column in the dataset. I have printed the first 1000 characters of the descriptions file below, but we'll get back to this one.

In [3]:
description = open('data/data_description.txt')

print(description.read(1000))

description.close()

MSSubClass: Identifies the type of dwelling involved in the sale.

        20	1-STORY 1946 & NEWER ALL STYLES
        30	1-STORY 1945 & OLDER
        40	1-STORY W/FINISHED ATTIC ALL AGES
        45	1-1/2 STORY - UNFINISHED ALL AGES
        50	1-1/2 STORY FINISHED ALL AGES
        60	2-STORY 1946 & NEWER
        70	2-STORY 1945 & OLDER
        75	2-1/2 STORY ALL AGES
        80	SPLIT OR MULTI-LEVEL
        85	SPLIT FOYER
        90	DUPLEX - ALL STYLES AND AGES
       120	1-STORY PUD (Planned Unit Development) - 1946 & NEWER
       150	1-1/2 STORY PUD - ALL AGES
       160	2-STORY PUD - 1946 & NEWER
       180	PUD - MULTILEVEL - INCL SPLIT LEV/FOYER
       190	2 FAMILY CONVERSION - ALL STYLES AND AGES

MSZoning: Identifies the general zoning classification of the sale.

       A	Agriculture
       C	Commercial
       FV	Floating Village Residential
       I	Industrial
       RH	Residential High Density
       RL	Residential Low Density
       RP	Residential Low Density Park
       RM